// <auto-generated />
using System;
using HomelabAPI.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HomelabAPI.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260929130000_SeedDevices")]
    partial class SeedDevices
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HomelabAPI.Core.Entities.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeviceGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DeviceStatus")
                        .HasColumnType("int");

                    b.Property<int>("DeviceType")
                        .HasColumnType("int");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasMaxLength(253)
                        .HasColumnType("nvarchar(253)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceGroupId");

                    b.HasIndex("Hostname")
                        .IsUnique();

                    b.ToTable("Devices");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3b9a7c10-5d2e-4f81-a6c4-000000000001"),
                            CreatedAt = new DateTime(2026, 9, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeviceGroupId = new Guid("8f5d2a4e-3c1b-4e6a-9b7d-1a2b3c4d5e01"),
                            DeviceStatus = 0,
                            DeviceType = 1,
                            Hostname = "pve-01",
                            IpAddress = "192.168.1.10",
                            Name = "Proxmox host"
                        },
                        new
                        {
                            Id = new Guid("3b9a7c10-5d2e-4f81-a6c4-000000000002"),
                            CreatedAt = new DateTime(2026, 9, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeviceGroupId = new Guid("8f5d2a4e-3c1b-4e6a-9b7d-1a2b3c4d5e01"),
                            DeviceStatus = 0,
                            DeviceType = 1,
                            Hostname = "nas-01",
                            IpAddress = "192.168.1.20",
                            Name = "NAS"
                        },
                        new
                        {
                            Id = new Guid("3b9a7c10-5d2e-4f81-a6c4-000000000003"),
                            CreatedAt = new DateTime(2026, 9, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeviceGroupId = new Guid("8f5d2a4e-3c1b-4e6a-9b7d-1a2b3c4d5e02"),
                            DeviceStatus = 0,
                            DeviceType = 2,
                            Hostname = "desktop-main",
                            IpAddress = "192.168.1.50",
                            Name = "Main desktop"
                        },
                        new
                        {
                            Id = new Guid("3b9a7c10-5d2e-4f81-a6c4-000000000004"),
                            CreatedAt = new DateTime(2026, 9, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeviceGroupId = new Guid("8f5d2a4e-3c1b-4e6a-9b7d-1a2b3c4d5e03"),
                            DeviceStatus = 0,
                            DeviceType = 2,
                            Hostname = "pi-livingroom",
                            IpAddress = "192.168.1.60",
                            Name = "Living room Pi"
                        },
                        new
                        {
                            Id = new Guid("3b9a7c10-5d2e-4f81-a6c4-000000000005"),
                            CreatedAt = new DateTime(2026, 9, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeviceStatus = 0,
                            DeviceType = 3,
                            Hostname = "phone-01",
                            Name = "Phone"
                        });
                });

            modelBuilder.Entity("HomelabAPI.Core.Entities.DeviceGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("DeviceGroups");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8f5d2a4e-3c1b-4e6a-9b7d-1a2b3c4d5e01"),
                            CreatedAt = new DateTime(2026, 9, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Rack-mounted servers and network gear",
                            Name = "Server rack"
                        },
                        new
                        {
                            Id = new Guid("8f5d2a4e-3c1b-4e6a-9b7d-1a2b3c4d5e02"),
                            CreatedAt = new DateTime(2026, 9, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Desk computers and peripherals",
                            Name = "Office"
                        },
                        new
                        {
                            Id = new Guid("8f5d2a4e-3c1b-4e6a-9b7d-1a2b3c4d5e03"),
                            CreatedAt = new DateTime(2026, 9, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Media and smart home devices",
                            Name = "Living room"
                        });
                });

            modelBuilder.Entity("HomelabAPI.Core.Entities.Device", b =>
                {
                    b.HasOne("HomelabAPI.Core.Entities.DeviceGroup", "DeviceGroup")
                        .WithMany("Devices")
                        .HasForeignKey("DeviceGroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DeviceGroup");
                });

            modelBuilder.Entity("HomelabAPI.Core.Entities.DeviceGroup", b =>
                {
                    b.Navigation("Devices");
                });
#pragma warning restore 612, 618
        }
    }
}
